# Fichas fijas de cada procedimiento (formato aprobado por el Dr. Gio): qué es, para quién es (✅),
# con qué se puede combinar, recuperación y quién lo realiza. La IA elige la ficha con <<<FICHA:clave>>>.
_PIE = "👨‍⚕️ La realiza el Dr. Gio con *anestesiólogo* y en *clínica certificada*"


def _ficha(titulo, que_es, ideal, combina, recuperacion):
    txt = f"{que_es} ✨\n\nPor lo general es ideal para ti si:\n" + "\n".join(f"✅ {x}" for x in ideal)
    if combina:
        txt += f"\n\n🔗 {combina}"
    return txt + f"\n\n⏱️ *Recuperación:* {recuperacion}\n{_PIE}"


FICHAS = {
    'abdominoplastia': _ficha('Abdominoplastia',
        "La *abdominoplastia* retira el *exceso de piel y grasa* del abdomen y, cuando es necesario, *repara los músculos* separados. El resultado es un abdomen *plano y firme*",
        ["Tienes *piel flácida o colgante*, por ejemplo después de *embarazos* o de *bajar mucho de peso*",
         "Notas el abdomen *abultado aunque hagas ejercicio*",
         "Tienes *estrías o piel sobrante* debajo del ombligo",
         "Estás en un *peso estable* y no piensas tener más embarazos pronto"],
        "Se puede *combinar* con *lipoescultura 360* (lipoabdominoplastia) para definir cintura y espalda, y con *lipotransferencia glútea* para dar volumen a los glúteos con tu propia grasa.",
        "actividades suaves en *2 a 3 semanas*; el Dr. Gio te da el plan exacto en la valoración"),
    'lipoabdominoplastia': _ficha('Lipoabdominoplastia',
        "La *lipoabdominoplastia* combina la *abdominoplastia* (retira piel y grasa sobrante y repara los músculos) con la *lipoescultura* de cintura, espalda y flancos, para un contorno *completo y armónico*",
        ["Tienes *piel sobrante* en el abdomen después de *embarazos* o *pérdida de peso*",
         "Además tienes *grasa localizada* en cintura, espalda o flancos",
         "Quieres un cambio *integral* del contorno en una sola cirugía",
         "Estás en un *peso estable*"],
        "Se puede *complementar* con *lipotransferencia glútea* para dar forma y volumen a los glúteos.",
        "actividades suaves en *2 a 3 semanas*; el Dr. Gio te da el plan exacto en la valoración"),
    'lipoescultura': _ficha('Lipoescultura 360',
        "La *lipoescultura 360* retira la *grasa localizada* de abdomen, cintura, espalda y flancos para *definir y armonizar tu silueta*",
        ["Tienes *grasa localizada* que no se va con dieta ni ejercicio",
         "Quieres *afinar la cintura* y definir tu figura",
         "Tienes *buena elasticidad de piel*",
         "Estás *cerca de tu peso ideal*"],
        "Se puede *combinar* con *lipotransferencia glútea* (tu propia grasa para dar volumen a los glúteos) y, si hay piel sobrante en el abdomen, con *abdominoplastia*.",
        "actividades suaves en *1 a 2 semanas* con faja y drenajes"),
    'lipotransferencia': _ficha('Lipotransferencia glútea',
        "La *lipotransferencia glútea* usa *tu propia grasa*, obtenida con lipoescultura, para dar *volumen y forma* a los glúteos de manera *natural*",
        ["Quieres *más volumen o proyección* en los glúteos",
         "Prefieres un resultado *natural, sin implantes*",
         "Tienes *grasa disponible* en abdomen, cintura o espalda",
         "Estás en un *peso estable*"],
        "Se realiza junto con la *lipoescultura 360* y se puede combinar con *abdominoplastia*.",
        "actividades suaves en *1 a 2 semanas*, con cuidados especiales al sentarte"),
    'mamoplastia_aumento': _ficha('Mamoplastia de aumento',
        "La *mamoplastia de aumento* aumenta el *volumen y mejora la forma* de los senos con *implantes*, elegidos según tu anatomía",
        ["Sientes que tus senos son *pequeños* para tu cuerpo",
         "Perdiste volumen después de *embarazos, lactancia* o *pérdida de peso*",
         "Tienes *asimetría* entre un seno y otro",
         "Quieres un escote más *lleno y armónico*"],
        "Si hay *caída* del seno se combina con *pexia* (levantamiento), y se puede hacer junto con *abdominoplastia* o *lipoescultura* (mommy makeover).",
        "actividades suaves en *1 semana*, con sostén postquirúrgico"),
    'pexia': _ficha('Pexia mamaria',
        "La *pexia mamaria* *levanta* los senos y reposiciona la areola; si se desea más volumen se hace *con implantes*",
        ["Tus senos están *caídos* o la areola apunta hacia abajo",
         "Hubo cambios después de *embarazos, lactancia* o *pérdida de peso*",
         "Quieres senos más *firmes y en su lugar*",
         "Estás en un *peso estable*"],
        "Se puede hacer *con implantes* para dar volumen, y combinar con *abdominoplastia* o *lipoescultura*.",
        "actividades suaves en *1 a 2 semanas*, con sostén postquirúrgico"),
    'reduccion': _ficha('Mamoplastia de reducción',
        "La *mamoplastia de reducción* disminuye el *tamaño y el peso* de los senos y los deja *levantados y proporcionados*",
        ["Tus senos son *muy grandes* para tu cuerpo",
         "Tienes *dolor de espalda, cuello u hombros* o marcas de los tirantes",
         "Te cuesta hacer ejercicio o encontrar ropa",
         "Quieres senos más *livianos y firmes*"],
        "Se puede combinar con *lipoescultura* o *abdominoplastia*.",
        "actividades suaves en *1 a 2 semanas*, con sostén postquirúrgico"),
    'explantacion': _ficha('Explantación mamaria',
        "La *explantación mamaria* retira los *implantes* (y la cápsula cuando es necesario), y si se requiere se acompaña de *levantamiento* para que el seno quede con buena forma",
        ["Quieres *retirar o cambiar* tus implantes",
         "Tienes *molestias*, endurecimiento o cambios en los implantes",
         "Ya no te sientes a gusto con el tamaño",
         "Quieres volver a un resultado más *natural*"],
        "Se puede combinar con *pexia* (levantamiento) o con *cambio de implantes*.",
        "actividades suaves en *1 a 2 semanas*, con sostén postquirúrgico"),
    'ginecomastia': _ficha('Ginecomastia',
        "La cirugía de *ginecomastia* retira la *grasa* y, si es necesario, el *tejido glandular* del pecho masculino para dejarlo *plano y definido*",
        ["Tienes *aumento del pecho* que no mejora con ejercicio",
         "Te incomoda usar camisetas o estar sin camisa",
         "Estás en un *peso estable*",
         "Quieres un pecho más *masculino y definido*"],
        "Se puede combinar con *lipoescultura* de abdomen y flancos.",
        "es *ambulatoria*; retomas actividades en *pocos días*, con chaleco compresivo"),
    'blefaroplastia': _ficha('Blefaroplastia',
        "La *blefaroplastia* retira el *exceso de piel y bolsas* de los párpados para una mirada *descansada y fresca*",
        ["Tienes *párpados caídos* o piel sobrante",
         "Tienes *bolsas* debajo de los ojos",
         "Te ves *cansada(o)* aunque hayas descansado",
         "En algunos casos la piel *molesta para ver*"],
        "Se puede combinar con *lipo de papada* u otros procedimientos faciales.",
        "inflamación leve por *1 a 2 semanas*"),
    'papada': _ficha('Lipo de papada',
        "La *lipo de papada* retira la *grasa acumulada* debajo del mentón para definir el *contorno del cuello y la mandíbula*",
        ["Tienes *papada* que no mejora con dieta ni ejercicio",
         "Quieres un *perfil* y una mandíbula más definidos",
         "Tienes *buena elasticidad* de piel (si no, se usa tecnología de retracción)",
         "Estás en un *peso estable*"],
        "Se puede combinar con *blefaroplastia* u otros procedimientos faciales.",
        "es *ambulatoria*; inflamación leve por *1 semana*, con mentonera"),
    'otoplastia': _ficha('Otoplastia',
        "La *otoplastia* corrige las *orejas despegadas* o con forma irregular para que queden *proporcionadas*",
        ["Tus orejas son *prominentes o despegadas*",
         "Hay *asimetría* entre una oreja y otra",
         "Te incomoda llevar el cabello recogido",
         "Quieres un perfil más *armónico*"],
        None,
        "actividades suaves en *pocos días*, con balaca protectora"),
    'abdominoplastia_inversa': _ficha('Abdominoplastia inversa',
        "La *abdominoplastia inversa* trata la *flacidez de la parte alta del abdomen*, por encima del ombligo, con la cicatriz escondida en el *surco debajo de los senos*",
        ["Tienes *piel suelta en la parte alta* del abdomen",
         "La parte baja del abdomen está *bien*",
         "Te vas a hacer o te interesa una *cirugía de senos*",
         "Estás en un *peso estable*"],
        "Se combina con frecuencia con *cirugía mamaria* y con *lipoescultura*.",
        "actividades suaves en *2 semanas*; el Dr. Gio te da el plan exacto en la valoración"),
    'mommy_makeover': _ficha('Mommy Makeover',
        "El *Mommy Makeover* combina en una sola cirugía los procedimientos que *devuelven la forma después de los embarazos*: abdomen, contorno y senos",
        ["Tuviste *embarazos* y notas cambios en abdomen y senos",
         "Tienes *piel sobrante* en el abdomen y *grasa localizada*",
         "Tus senos perdieron *volumen o firmeza*",
         "Ya *no piensas tener más embarazos*"],
        "Suele incluir *abdominoplastia*, *lipoescultura* y *mamoplastia* (aumento o pexia); se puede sumar *lipotransferencia glútea*.",
        "actividades suaves en *2 a 3 semanas*; el Dr. Gio te da el plan exacto en la valoración"),
    'lifting_extremidades': _ficha('Lifting de brazos o piernas',
        "El *lifting de brazos o piernas* retira la *piel sobrante y flácida* para que queden *firmes y definidos*",
        ["Tienes *piel colgante* en brazos o muslos",
         "Pasó después de *bajar mucho de peso*",
         "La flacidez *no mejora* con ejercicio",
         "Estás en un *peso estable*"],
        "Se puede combinar con *lipoescultura* de la zona.",
        "actividades suaves en *2 semanas*, con prendas compresivas"),
    'gluteoplastia_implante': _ficha('Gluteoplastia con implante',
        "La *gluteoplastia con implante* da *volumen y proyección* a los glúteos con *implantes* especiales",
        ["Quieres *más volumen* en los glúteos",
         "Tienes *poca grasa* para hacer lipotransferencia",
         "Buscas un cambio de *forma y proyección*",
         "Estás en un *peso estable*"],
        "Se puede combinar con *lipoescultura* para definir la cintura.",
        "cuidados especiales al sentarte durante las primeras *semanas*"),
}


def expandir_fichas(texto):
    """Reemplaza <<<FICHA:clave>>> por la ficha fija. Devuelve (texto, hubo_ficha)."""
    import re
    hubo = False

    def _rep(m):
        nonlocal hubo
        clave = m.group(1).strip().lower()
        if clave in FICHAS:
            hubo = True
            return FICHAS[clave]
        return ''
    texto = re.sub(r'<<<FICHA:([a-z_]+)>>>', _rep, texto)
    return texto, hubo
